version: 0.0.{build}
branches:
  only:
  - master

install:
  - if not exist "make.zip" curl -L -o make.zip http://gnuwin32.sourceforge.net/downlinks/make-bin-zip.php
  - if not exist "make-dep.zip" curl -L -o make-dep.zip http://gnuwin32.sourceforge.net/downlinks/make-dep-zip.php
  - if not exist "gcc-arm-none-eabi.zip" curl -L -o gcc-arm-none-eabi.zip https://launchpad.net/gcc-arm-embedded/4.8/4.8-2014-q1-update/+download/gcc-arm-none-eabi-4_8-2014q1-20140314-win32.zip
  - if not exist "C:\python27" cinst python27
  - rename c:\python27\python.exe python2.exe
  - if not exist "C:\strawberry" cinst strawberryperl #once I workout how to install Digest::SHA for perl, this won't be required
  - set PATH=C:\strawberry\perl\bin;C:\strawberry\perl\site\bin;C:\strawberry\c\bin;%PATH%
  - cpanm --installdeps Digest::SHA
  - unzip -o -q gcc-arm-none-eabi.zip -d c:\gcc\
  - unzip make.zip -d c:\gnuwin32\
  - unzip make-dep.zip -d c:\gnuwin32\
  - set PATH=C:\Program Files\git\bin;%PATH:C:\Program Files\git\bin;=% #move git to begining of PATH so find works correctly
  - set PATH=%PATH%;c:\gnuwin32\bin;c:\gcc\bin

cache:
  - gcc-arm-none-eabi.zip
  - make.zip
  - make-dep.zip

build_script:
  - make all -j3
  - make clean
  - cd applet
  - make -f Makefile.d02.032
  - cd ..
  - cd db
  - make all